module.exports={
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    PRODUCT_COLLECTION:'product',
    CATEGORY_COLLECTION:'category',
    BRAND_COLLECTION:'brand',
    CART_COLLECTION:'cart',
    WISHLIST_COLLECTION:'wishlist',
    ORDER_COLLECTION:'order'
}